# Generated by Django 3.0.2 on 2020-01-02 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_psoted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 20, 59, 19, 99630, tzinfo=utc)),
        ),
    ]
