# Generated by Django 3.0.2 on 2020-01-02 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200102_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_psoted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 21, 4, 5, 808729, tzinfo=utc)),
        ),
    ]
