# Generated by Django 3.0.2 on 2020-01-02 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200103_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_psoted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 21, 7, 7, 230768, tzinfo=utc)),
        ),
    ]
