# Generated by Django 3.0.2 on 2020-01-16 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200113_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_psoted',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 12, 37, 42, 688604, tzinfo=utc)),
        ),
    ]
